/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CostCategory = "accessory" | "cleaning" | "commission" | "fee" | "improvement" | "labor" | "other" | "part" | "repair" | "shipping" | "tax";

export type CostStatus = "estimated" | "paid" | "pending";

export type FinancialAccountType = "bank" | "cash" | "digital_wallet" | "other";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentStatus = "paid" | "pending" | "refunded";

export type ProductStatus = "advertised" | "delivered" | "evaluation" | "preparation" | "ready" | "received" | "repair" | "reserved" | "sold";

export type RepairStatus = "approved" | "cancelled" | "completed" | "draft" | "in_progress" | "quoted" | "rejected" | "waiting_part";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface Businesses {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  logoUrl: string | null;
  name: string;
  ownerUserId: number;
  updatedAt: Generated<Timestamp>;
}

export interface CompanyEntries {
  active: Generated<boolean>;
  amount: Numeric;
  businessId: Int8;
  createdAt: Generated<Timestamp>;
  entryType: string;
  expectedDate: Timestamp;
  id: Generated<Int8>;
  name: string;
  notes: string | null;
  ownerUserId: number;
  realized: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
}

export interface CreditCards {
  active: Generated<boolean>;
  availableLimit: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  includeAsAvailable: Generated<boolean>;
  institution: string | null;
  name: string;
  ownerUserId: number;
  totalLimit: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface FinancialAccounts {
  accountType: FinancialAccountType;
  active: Generated<boolean>;
  balance: Generated<Numeric>;
  businessId: Int8 | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  institution: string | null;
  name: string;
  notes: string | null;
  ownerUserId: number;
  updatedAt: Generated<Timestamp>;
}

export interface InvestmentAssets {
  active: Generated<boolean>;
  assetType: string;
  averageCost: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  currentUnitPrice: Generated<Numeric>;
  id: Generated<Int8>;
  name: string;
  notes: string | null;
  ownerUserId: number;
  quantity: Generated<Numeric>;
  symbol: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface InvestmentValuations {
  assetId: Int8;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  quantity: Numeric;
  unitPrice: Numeric;
  valuationMonth: Timestamp;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface PatrimonySnapshots {
  businessValue: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  investmentValue: Generated<Numeric>;
  ownerUserId: Int8;
  personalValue: Generated<Numeric>;
  snapshotDate: Timestamp;
  totalValue: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface PersonalAssets {
  acquisitionDate: Timestamp | null;
  active: Generated<boolean>;
  amountPaid: Generated<Numeric>;
  assetType: string;
  createdAt: Generated<Timestamp>;
  currentValue: Generated<Numeric>;
  description: string | null;
  id: Generated<Int8>;
  name: string;
  notes: string | null;
  outstandingDebt: Generated<Numeric>;
  ownershipPercentage: Numeric | null;
  ownerUserId: number;
  updatedAt: Generated<Timestamp>;
}

export interface PersonalEntries {
  active: Generated<boolean>;
  amount: Numeric;
  competenceMonth: Timestamp;
  createdAt: Generated<Timestamp>;
  entryType: string;
  id: Generated<Int8>;
  name: string;
  notes: string | null;
  ownerUserId: number;
  recurring: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
}

export interface ProductCosts {
  amount: Numeric;
  category: CostCategory;
  createdAt: Generated<Timestamp>;
  description: string;
  id: Generated<Int8>;
  incurredOn: Generated<Timestamp>;
  notes: string | null;
  productId: Int8;
  providerName: string | null;
  status: Generated<CostStatus>;
}

export interface ProductGroups {
  active: Generated<boolean>;
  businessId: Int8 | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<Int8>;
  name: string;
  ownerUserId: number;
  updatedAt: Generated<Timestamp>;
}

export interface Products {
  accessories: string | null;
  aestheticCondition: string | null;
  batteryHealth: number | null;
  brand: string | null;
  businessId: Int8 | null;
  capacity: string | null;
  color: string | null;
  conditionLabel: Generated<string>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  functionalCondition: string | null;
  groupId: Int8 | null;
  id: Generated<Int8>;
  imeiSerial: string | null;
  internalCode: string;
  model: string | null;
  name: string;
  notes: string | null;
  ownerUserId: number;
  purchaseDate: Timestamp;
  purchaseOrigin: string | null;
  purchasePaymentMethod: string | null;
  purchasePrice: Numeric;
  segment: string;
  sellerProfileUrl: string | null;
  sellerReference: string | null;
  soldAt: Timestamp | null;
  sourceLocation: string | null;
  sourcePlatform: string | null;
  status: Generated<ProductStatus>;
  storageLocation: string | null;
  subtitle: string | null;
  supplierContact: string | null;
  supplierName: string | null;
  targetPrice: Numeric | null;
  updatedAt: Generated<Timestamp>;
}

export interface ProductStatusHistory {
  changedAt: Generated<Timestamp>;
  changedBy: number;
  fromStatus: ProductStatus | null;
  id: Generated<Int8>;
  note: string | null;
  productId: Int8;
  toStatus: ProductStatus;
}

export interface ProfitTransferRules {
  active: Generated<boolean>;
  businessId: Int8 | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  ownerUserId: number;
  percentage: Numeric;
  sourceType: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProfitTransfers {
  amount: Numeric;
  businessId: Int8 | null;
  competenceMonth: Timestamp;
  createdAt: Generated<Timestamp>;
  depositedAt: Timestamp | null;
  id: Generated<Int8>;
  label: string;
  ownerUserId: Int8;
  personalEntryId: Int8 | null;
  recognitionMonth: Timestamp;
  ruleId: Int8;
  status: Generated<string>;
  transferKey: string;
  updatedAt: Generated<Timestamp>;
}

export interface RepairOrders {
  businessId: Int8 | null;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  defectDescription: string;
  expectedCompletion: Timestamp | null;
  finalAmount: Numeric | null;
  id: Generated<Int8>;
  knownAtPurchase: Generated<boolean>;
  notes: string | null;
  ownerUserId: number;
  productId: Int8;
  quotedAmount: Numeric | null;
  status: Generated<RepairStatus>;
  technicianName: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface SalePayments {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  dueDate: Timestamp | null;
  id: Generated<Int8>;
  method: string;
  paidAt: Timestamp | null;
  saleId: Int8;
  status: Generated<PaymentStatus>;
}

export interface Sales {
  businessId: Int8 | null;
  cancelledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  customerContact: string | null;
  customerName: string;
  discount: Generated<Numeric>;
  fees: Generated<Numeric>;
  id: Generated<Int8>;
  notes: string | null;
  ownerUserId: number;
  productId: Int8;
  salePrice: Numeric;
  soldAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  activeBusinessId: Int8 | null;
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  businesses: Businesses;
  companyEntries: CompanyEntries;
  creditCards: CreditCards;
  financialAccounts: FinancialAccounts;
  investmentAssets: InvestmentAssets;
  investmentValuations: InvestmentValuations;
  loginAttempts: LoginAttempts;
  patrimonySnapshots: PatrimonySnapshots;
  personalAssets: PersonalAssets;
  personalEntries: PersonalEntries;
  productCosts: ProductCosts;
  productGroups: ProductGroups;
  products: Products;
  productStatusHistory: ProductStatusHistory;
  profitTransferRules: ProfitTransferRules;
  profitTransfers: ProfitTransfers;
  repairOrders: RepairOrders;
  salePayments: SalePayments;
  sales: Sales;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const ProductStatusArrayValues: [ProductStatus, ...ProductStatus[]] = ["advertised","delivered","evaluation","preparation","ready","received","repair","reserved","sold"];
export const CostStatusArrayValues: [CostStatus, ...CostStatus[]] = ["estimated","paid","pending"];
export const CostCategoryArrayValues: [CostCategory, ...CostCategory[]] = ["accessory","cleaning","commission","fee","improvement","labor","other","part","repair","shipping","tax"];
export const PaymentStatusArrayValues: [PaymentStatus, ...PaymentStatus[]] = ["paid","pending","refunded"];
export const RepairStatusArrayValues: [RepairStatus, ...RepairStatus[]] = ["approved","cancelled","completed","draft","in_progress","quoted","rejected","waiting_part"];
export const FinancialAccountTypeArrayValues: [FinancialAccountType, ...FinancialAccountType[]] = ["bank","cash","digital_wallet","other"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
