import { useMemo, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Building2, Camera, Car, ChevronLeft, ChevronRight, CreditCard, Handshake, House, Landmark, Pencil, Plus, Trash2, TrendingUp, WalletCards } from "lucide-react";
import { Button } from "./Button";
import { Input } from "./Input";
import { postAction } from "../endpoints/app/action_POST.schema";
import styles from "./ExpansionPanels.module.css";

const brl=(n:any)=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const shortMonth=(m:string)=>new Intl.DateTimeFormat("pt-BR",{month:"short",year:"2-digit",timeZone:"UTC"}).format(new Date(m+"-02T00:00:00Z")).replace(".","");
const moveMonth=(month:string,n:number)=>{const d=new Date(month+"-02T00:00:00Z");d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,7)};
function Shell({title,subtitle,action,children}:any){return <section className={styles.panel}><div className={styles.head}><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div>{children}</section>}
function Modal({title,children,close,submit,busy,error}:any){return <div className={styles.backdrop} onMouseDown={close}><form className={styles.modal} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className={styles.head}><h2>{title}</h2><button type="button" onClick={close}>×</button></div>{children}{error&&<p className={styles.formError}>{error}</p>}<div className={styles.actions}><Button type="button" variant="outline" onClick={close}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?"Salvando…":"Salvar"}</Button></div></form></div>}
function Field({name,label,type="text",value,required=false}:any){return <label>{label}<Input name={name} type={type} step={type==="number"?"0.01":undefined} defaultValue={value??""} required={required}/></label>}

function PatrimonyChart({d}:any){
 const qc=useQueryClient(),[editor,setEditor]=useState(false),[source,setSource]=useState(d.user.avatarUrl||""),[zoom,setZoom]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0),[error,setError]=useState("");
 const m=useMutation({mutationFn:postAction,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["app-data"]});setEditor(false);setError("")},onError:(e:any)=>setError(e?.message||"Não foi possível salvar a foto")});
 const asset=(type:string)=>Number(d.personalAssets?.byType?.find((a:any)=>a.type===type)?.value||0);
 const investmentLabels:any={stock:"Ações",crypto:"Criptomoedas",fund:"Fundos",property:"Imóveis de investimento",fixed_income:"Renda fixa",other:"Outros investimentos"};
 const colors=["#20e978","#19a7ff","#ff146c","#7d8dff","#f6bd4b","#18a8ff","#50f0bd","#b559ff","#ff5c8d"];
 const base=[{name:"Empresas",value:Number(d.patrimony.businessValue||0)},{name:"Caixa pessoal + crédito",value:Math.max(0,Number(d.personal.availableWithCards||0))},{name:"Imóveis",value:asset("property")},{name:"Veículos",value:asset("vehicle")},{name:"Participações acionárias",value:asset("equity")}];
 const categories=[...base,...(d.investments?.composition||[]).map((a:any)=>({name:investmentLabels[a.type]||a.type,value:Number(a.value||0)}))].map((a:any,i:number)=>({...a,color:colors[i%colors.length]}));
 const total=Math.max(0,categories.reduce((s:number,a:any)=>s+a.value,0));let acc=0;
 const gradient=categories.filter((a:any)=>a.value>0).map((a:any)=>{const start=total?acc/total*360:0;acc+=a.value;return `${a.color} ${start}deg ${total?acc/total*360:0}deg`}).join(",");
 const positive=categories.filter((a:any)=>a.value>0);let angle=0;
 const geometry=positive.map((a:any)=>{const start=total?angle/total*360:0;angle+=a.value;const end=total?angle/total*360:0,mid=(start+end)/2,rad=mid*Math.PI/180,pointX=380+Math.sin(rad)*131,pointY=165-Math.cos(rad)*131;return {...a,start,end,mid,pointX,pointY,right:pointX>=380}});
 const place=(rows:any[])=>{const sorted=[...rows].sort((a,b)=>a.pointY-b.pointY),top=58,bottom=275;return sorted.map((a,i)=>({...a,targetY:sorted.length===1?166:top+i*(bottom-top)/(sorted.length-1)}))};
 const callouts=[...place(geometry.filter(a=>!a.right)),...place(geometry.filter(a=>a.right))];
 const zero=categories.filter((a:any)=>a.value<=0).map((a:any)=>a.name);
 const choose=(e:any)=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/"))return setError("Selecione uma imagem válida.");const reader=new FileReader();reader.onload=()=>{setSource(String(reader.result));setZoom(1);setX(0);setY(0);setError("")};reader.readAsDataURL(file)};
 const save=async(e:any)=>{e.preventDefault();if(!source)return m.mutate({action:"updateAvatar",avatarDataUrl:""});const img=new Image();img.onload=()=>{const size=512,canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d")!;const scale=Math.max(size/img.width,size/img.height)*zoom,w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2+x*size/260,(size-h)/2+y*size/260,w,h);m.mutate({action:"updateAvatar",avatarDataUrl:canvas.toDataURL("image/jpeg",.88)})};img.onerror=()=>setError("Não foi possível processar a imagem.");img.src=source};
 return <><section className={styles.wealthCard}>
  <div className={styles.wealthHeading}><small>PATRIMÔNIO TOTAL</small><strong>{brl(total)}</strong><p>Composição pelo valor atual líquido</p></div>
  <div className={styles.calloutStage}><svg className={styles.calloutLines} viewBox="0 0 760 330" role="img" aria-label="Composição detalhada do patrimônio"><defs>{callouts.map((a:any,i:number)=><marker key={a.name} id={"wealth-arrow-"+i} viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L8 4L0 8Z" fill={a.color}/></marker>)}</defs>{callouts.map((a:any,i:number)=>{const endX=a.right?625:135,elbowX=a.right?535:225,textX=a.right?635:125;return <g key={a.name}><polyline points={`${endX},${a.targetY} ${elbowX},${a.targetY} ${a.pointX},${a.pointY}`} fill="none" stroke={a.color} strokeWidth="1.5" markerEnd={`url(#wealth-arrow-${i})`}/><circle cx={endX} cy={a.targetY} r="4" fill={a.color}/><text x={textX} y={a.targetY-8} textAnchor={a.right?"start":"end"}><tspan className={styles.calloutName}>{a.name}</tspan><tspan x={textX} dy="17" className={styles.calloutPercent}>{total?((a.value/total)*100).toFixed(1):"0,0"}%</tspan><tspan x={textX} dy="14" className={styles.calloutValue}>{brl(a.value)}</tspan></text></g>})}</svg><div className={styles.wealthCenter}><div className={styles.wealthRing} style={{background:total&&gradient?`conic-gradient(${gradient})`:"rgba(255,255,255,.12)"}}><button type="button" className={styles.portrait} onClick={()=>{setSource(d.user.avatarUrl||"");setEditor(true)}} aria-label="Alterar foto central">{d.user.avatarUrl?<img src={d.user.avatarUrl} alt="Foto do usuário"/>:<><Camera/><span>Adicionar foto</span></>}</button></div><button type="button" className={styles.photoAction} onClick={()=>{setSource(d.user.avatarUrl||"");setEditor(true)}}><Camera size={13}/>{d.user.avatarUrl?"Editar foto":"Escolher foto"}</button></div></div>
  {zero.length>0&&<p className={styles.zeroCategories}>Sem valor atual e, portanto, sem fatia no gráfico: {zero.join(" · ")}</p>}
 </section>{editor&&<Modal title="Foto do patrimônio" close={()=>setEditor(false)} busy={m.isPending} error={error} submit={save}><div className={styles.photoEditor}><div className={styles.cropFrame}>{source?<img src={source} style={{transform:`translate(${x}px,${y}px) scale(${zoom})`}}/>:<div><Camera/><span>Escolha uma foto</span></div>}</div><label className={styles.fileButton}>Selecionar imagem<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choose}/></label><label>Ampliação <input type="range" min="1" max="3" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Posição horizontal <input type="range" min="-100" max="100" value={x} onChange={e=>setX(Number(e.target.value))}/></label><label>Posição vertical <input type="range" min="-100" max="100" value={y} onChange={e=>setY(Number(e.target.value))}/></label><div className={styles.photoTools}><Button type="button" variant="outline" onClick={()=>{setZoom(1);setX(0);setY(0)}}>Centralizar</Button>{d.user.avatarUrl&&<Button type="button" variant="outline" onClick={()=>{setSource("");setZoom(1);setX(0);setY(0)}}>Remover foto</Button>}</div></div></Modal>}</>
}

function Sparkline({points,color="#59e6a2"}:any){const vals=(points||[]).map((x:any)=>Number(x.value||0)),min=Math.min(0,...vals),max=Math.max(1,...vals),span=max-min;const coords=vals.map((v:number,i:number)=>`${vals.length===1?50:i/(vals.length-1)*100},${34-(v-min)/span*28}`).join(" ");return <svg className={styles.spark} viewBox="0 0 100 40" preserveAspectRatio="none"><line x1="0" x2="100" y1={34-(-min)/span*28} y2={34-(-min)/span*28}/><polyline points={coords||"0,34 100,34"} style={{stroke:color}}/></svg>}
function MiniDashboard({d}:any){
 const personal=d.patrimony?.personalTrend||[],composition=d.investments?.composition||[],total=Math.max(1,composition.reduce((s:number,x:any)=>s+Number(x.value),0));let acc=0;const colors=["#59e6a2","#f8b55b","#8eb7ff","#cf8eff","#ff7e83","#65d4dc"];const gradient=composition.map((x:any,i:number)=>{const start=acc/total*360;acc+=Number(x.value);return `${colors[i%colors.length]} ${start}deg ${acc/total*360}deg`}).join(",");
 return <div className={styles.miniGrid}>
  <section className={styles.miniSection}><div className={styles.miniTitle}><div><small>EMPRESAS</small><b>Evolução do lucro</b></div><span>por competência de compra</span></div><div className={styles.businessSparks}>{d.businesses.map((b:any)=><article key={b.id}><div><b>{b.name}</b><strong>{brl((b.trend||[]).reduce((s:number,x:any)=>s+Number(x.value),0))}</strong></div><Sparkline points={b.trend}/><small>{b.pendingTransferCount?b.pendingTransferCount+" pró-labore pendente":"Sem repasse pendente"}</small></article>)}</div></section>
  <section className={styles.miniSection}><div className={styles.miniTitle}><div><small>CONTAS PESSOAIS</small><b>Receitas x despesas</b></div><span>mês a mês</span></div><div className={styles.personalBars}>{personal.slice(-6).map((x:any)=>{const peak=Math.max(1,...personal.flatMap((p:any)=>[Number(p.income),Number(p.expenses)]));return <div key={x.month}><span><i style={{height:Math.max(3,Number(x.income)/peak*62)}}/><i style={{height:Math.max(3,Number(x.expenses)/peak*62)}}/></span><small>{shortMonth(x.month).split("/")[0]}</small></div>})}</div><div className={styles.barLegend}><span><i/>Receitas</span><span><i/>Despesas</span></div></section>
  <section className={styles.miniSection}><div className={styles.miniTitle}><div><small>INVESTIMENTOS</small><b>Composição da carteira</b></div><span>{brl(d.investments.currentValue)}</span></div><div className={styles.composition}><div className={styles.donut} style={{background:composition.length?`conic-gradient(${gradient})`:"rgba(255,255,255,.12)"}}><i/></div><div>{composition.length?composition.map((x:any,i:number)=><span key={x.type}><i style={{background:colors[i%colors.length]}}/><b>{x.type.replace("_"," ")}</b><small>{Math.round(Number(x.value)/total*100)}%</small></span>):<p>Cadastre investimentos para visualizar.</p>}</div></div></section>
 </div>
}

export function HomePanel({d,navigate}:any){
 return <div className={styles.home}>
  <div className={styles.welcome}><small>CENTRAL DE GESTÃO</small><h2>Olá, {d.user.displayName.split(" ")[0]}</h2><p>Escolha uma área ou acompanhe a evolução do seu patrimônio.</p></div>
  <div className={styles.homeBody}><div className={styles.homeChoices}><div className={styles.homeGrid}>
   <button type="button" onClick={()=>navigate("pessoal")}><i><WalletCards/></i><span><b>Contas pessoais</b><small>Receitas, despesas, cartões e pró-labore</small></span><strong>→</strong></button>
   <button type="button" onClick={()=>navigate("empresas")}><i><Building2/></i><span><b>Empresas</b><small>{d.businesses.length} empresa(s) · estoque, vendas e financeiro</small></span><strong>→</strong></button>
   <button type="button" onClick={()=>navigate("patrimonio_pessoal")}><i><House/></i><span><b>Patrimônio pessoal</b><small>Imóveis, veículos e participações acionárias</small></span><strong>→</strong></button>
   <button type="button" onClick={()=>navigate("investimentos")}><i><TrendingUp/></i><span><b>Carteira de investimentos</b><small>Ações, criptomoedas e outros ativos</small></span><strong>→</strong></button>
  </div></div><PatrimonyChart d={d}/></div><MiniDashboard d={d}/>
 </div>
}

export function CompaniesPanel({d,onOpen}:any){
 const[modal,setModal]=useState<any>(null),[error,setError]=useState(""),qc=useQueryClient();const m=useMutation({mutationFn:postAction,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["app-data"]});setModal(null);setError("")},onError:(e:any)=>setError(e?.message||"Não foi possível concluir a operação")});
 const act=async(body:any)=>{await m.mutateAsync(body)};
 return <><Shell title="Minhas empresas" subtitle="Cada empresa possui estoque, vendas, contas e resultados totalmente separados." action={<Button onClick={()=>setModal({})}><Plus size={15}/> Nova empresa</Button>}>
  <div className={styles.companyGrid}>{d.businesses.map((b:any)=><article className={String(b.id)===String(d.activeBusiness.id)?styles.selected:""} key={b.id}>
   <div className={styles.logo}>{b.logoUrl?<img src={b.logoUrl}/>:<Building2/>}</div><div><small>EMPRESA</small><h3>{b.name}</h3><p>{b.productCount} produtos cadastrados</p><b>Lucro do mês anterior: {brl(b.previousMonthProfit)}</b>{b.pendingTransferCount>0&&<em className={styles.pendingTag}>{b.pendingTransferCount} repasse(s) pendente(s) · {brl(b.pendingTransferAmount)}</em>}</div>
   <div className={styles.cardActions}><Button variant="outline" onClick={async()=>{await act({action:"switchBusiness",businessId:String(b.id)});onOpen()}}>Abrir</Button><button type="button" onClick={()=>setModal(b)} title="Editar"><Pencil size={15}/></button><button type="button" onClick={async()=>{if(confirm("Arquivar esta empresa? Os dados serão preservados."))await act({action:"archiveBusiness",businessId:String(b.id)})}} title="Arquivar"><Trash2 size={15}/></button></div>
  </article>)}</div>
 </Shell>{modal&&<Modal title={modal.id?"Editar empresa":"Cadastrar empresa"} close={()=>setModal(null)} busy={m.isPending} submit={(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:"upsertBusiness",businessId:modal.id?String(modal.id):undefined,name:String(f.get("name")),logoUrl:String(f.get("logoUrl")||"")})}}><Field name="name" label="Nome da empresa" value={modal.name} required/><Field name="logoUrl" label="Link da logo (opcional)" value={modal.logoUrl}/></Modal>}</>
}

export function CompanyProLaboreNotice({d}:any){
 const[error,setError]=useState(""),qc=useQueryClient();const m=useMutation({mutationFn:postAction,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["app-data"]});setError("")},onError:(e:any)=>setError(e?.message||"Não foi possível confirmar o depósito")});
 const rows=(d.pendingTransfers||[]).filter((t:any)=>String(t.businessId)===String(d.activeBusiness.id));
 if(!rows.length)return null;
 return <div className={styles.transferAlerts}><div className={styles.transferIntro}><TrendingUp/><span><b>Pró-labore da {d.activeBusiness.name} aguardando confirmação</b><small>Confirme apenas se o depósito já foi realizado. O sistema não altera automaticamente nenhuma conta ou saldo.</small></span></div>{rows.map((t:any)=><article key={t.id}><span><small>{t.businessName}</small><b>{t.label}</b></span><strong>{brl(t.amount)}</strong><Button disabled={m.isPending} onClick={()=>m.mutate({action:"confirmProfitTransfer",transferId:String(t.id)})}>Confirmar que foi depositado</Button></article>)}{error&&<p className={styles.formError}>{error}</p>}</div>
}

export function PersonalPanel({d,onMonthChange}:any){
 const[modal,setModal]=useState<any>(null),[error,setError]=useState(""),qc=useQueryClient();
 const m=useMutation({mutationFn:postAction,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["app-data"]});setModal(null);setError("")},onError:(e:any)=>setError(e?.message||"Não foi possível salvar. Revise os dados.")});const p=d.personal;
 const remove=async(action:any,idKey:string,id:any)=>{if(confirm("Arquivar este registro?"))await m.mutateAsync({action,[idKey]:String(id)} as any)};
 const generated=useMemo(()=>[...(p.carryIn>0?[{id:"carry",name:p.carryLabel,amount:p.carryIn,entryType:"income",generated:true}]:[]),...(p.generatedIncome||[])],[p]);
 const monthControls=<div className={styles.monthControls}><button type="button" onClick={()=>onMonthChange(moveMonth(p.month,-1))} aria-label="Mês anterior"><ChevronLeft size={16}/></button><Input type="month" value={p.month} onChange={e=>onMonthChange(e.target.value)}/><button type="button" onClick={()=>onMonthChange(moveMonth(p.month,1))} aria-label="Próximo mês"><ChevronRight size={16}/></button></div>;
 return <>{monthControls}<div className={styles.summary}><article><WalletCards/><small>RECEITAS</small><strong>{brl(p.income)}</strong></article><article><Landmark/><small>DESPESAS</small><strong>{brl(p.expenses)}</strong></article><article><TrendingUp/><small>SOBRA PREVISTA + CRÉDITO</small><strong className={p.availableWithCards>=0?styles.green:styles.red}>{brl(p.availableWithCards)}</strong></article><article><CreditCard/><small>LIMITE DISPONÍVEL INCLUÍDO</small><strong>{brl(p.cardAvailability)}</strong></article></div>
 <Shell title={"Contas pessoais — "+p.label} subtitle="A sobra positiva é carregada automaticamente como receita do mês seguinte." action={<div className={styles.entryActions}><Button variant="outline" onClick={()=>{setError("");setModal({type:"entry",entryType:"income"})}}><Plus size={15}/> Receita</Button><Button onClick={()=>{setError("");setModal({type:"entry",entryType:"expense"})}}><Plus size={15}/> Despesa</Button></div>}>
  <div className={styles.twoCols}><div><h3>Receitas e despesas</h3>{[...generated,...p.entries].length?[...generated,...p.entries].map((x:any)=><div className={styles.row} key={x.id}><span><b>{x.name}</b><small>{x.generated?"Gerado automaticamente":x.entryType==="income"?"Receita":"Despesa"}{x.recurring?" · recorrente":""}</small></span><strong className={x.entryType==="income"?styles.green:styles.red}>{x.entryType==="income"?"+ ":"- "}{brl(x.amount)}</strong>{!x.generated&&<><button type="button" onClick={()=>{setError("");setModal({type:"entry",entryType:x.entryType,data:x})}}><Pencil size={14}/></button><button type="button" onClick={()=>remove("archivePersonalEntry","entryId",x.id)}><Trash2 size={14}/></button></>}</div>):<p className={styles.empty}>Nenhum lançamento neste mês.</p>}</div>
  <div><div className={styles.subhead}><h3>Cartões de crédito</h3><Button variant="outline" onClick={()=>{setError("");setModal({type:"card"})}}>+ Cartão</Button></div>{p.cards.length?p.cards.map((x:any)=><div className={styles.row} key={x.id}><span><b>{x.name}</b><small>Usado: {brl(Number(x.totalLimit)-Number(x.availableLimit))} · disponível: {brl(x.availableLimit)} · incluído automaticamente na Sobra prevista</small></span><button type="button" onClick={()=>{setError("");setModal({type:"card",data:x})}}><Pencil size={14}/></button><button type="button" onClick={()=>remove("archiveCreditCard","cardId",x.id)}><Trash2 size={14}/></button></div>):<p className={styles.empty}>Nenhum cartão cadastrado.</p>}</div></div>
 </Shell>
 <Shell title="Pró-labore realizado" subtitle="Só é reconhecido após a venda completa. Atrasos aparecem como compensação da competência original." action={<Button variant="outline" onClick={()=>{setError("");setModal({type:"rule"})}}>+ Regra</Button>}>
  {p.rules.length?p.rules.map((x:any)=><div className={styles.row} key={x.id}><span><b>{x.sourceName}</b><small>{Number(x.percentage)}% sobre {brl(x.base)} · {x.amount>0?"realizado neste mês":"aguardando venda elegível"}</small></span><strong>{brl(x.amount)}</strong><button type="button" onClick={()=>{setError("");setModal({type:"rule",data:x})}}><Pencil size={14}/></button><button type="button" onClick={()=>remove("archiveTransferRule","ruleId",x.id)}><Trash2 size={14}/></button></div>):<p className={styles.empty}>Nenhuma regra de pró-labore configurada.</p>}
 </Shell>
 {modal?.type==="entry"&&<Modal title={modal.entryType==="expense"?"Adicionar despesa":"Adicionar receita"} close={()=>setModal(null)} busy={m.isPending} error={error} submit={(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);m.mutate({action:"upsertPersonalEntry",entryId:modal.data?.id?String(modal.data.id):undefined,entryType:modal.entryType,name:String(f.get("name")),amount:Number(f.get("amount")),competenceMonth:String(f.get("competenceMonth")),recurring:f.get("recurring")==="on",notes:String(f.get("notes")||"")})}}><Field name="name" label="Descrição" value={modal.data?.name} required/><Field name="amount" label="Valor" type="number" value={modal.data?.amount} required/><Field name="competenceMonth" label="Mês de competência" type="month" value={modal.data?.competenceMonth?new Date(modal.data.competenceMonth).toISOString().slice(0,7):p.month} required/><label className={styles.check}><input type="checkbox" name="recurring" defaultChecked={modal.data?.recurring}/> Repetir nos meses seguintes</label><Field name="notes" label="Observações" value={modal.data?.notes}/></Modal>}
 {modal?.type==="card"&&<Modal title="Cartão de crédito" close={()=>setModal(null)} busy={m.isPending} error={error} submit={(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);m.mutate({action:"upsertCreditCard",cardId:modal.data?.id?String(modal.data.id):undefined,name:String(f.get("name")),institution:String(f.get("institution")||""),totalLimit:Number(f.get("totalLimit")),availableLimit:Number(f.get("availableLimit")),includeAsAvailable:true})}}><Field name="name" label="Nome do cartão" value={modal.data?.name} required/><Field name="institution" label="Banco/instituição" value={modal.data?.institution}/><Field name="totalLimit" label="Limite total" type="number" value={modal.data?.totalLimit} required/><Field name="availableLimit" label="Limite disponível agora" type="number" value={modal.data?.availableLimit} required/><p className={styles.cardNotice}>Todo limite disponível é somado automaticamente à Sobra prevista.</p></Modal>}
 {modal?.type==="rule"&&<Modal title="Regra de pró-labore" close={()=>setModal(null)} busy={m.isPending} error={error} submit={(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);const sourceType=String(f.get("sourceType"));m.mutate({action:"upsertTransferRule",ruleId:modal.data?.id?String(modal.data.id):undefined,sourceType:sourceType as any,businessId:sourceType==="business"?String(f.get("businessId")):undefined,percentage:Number(f.get("percentage"))})}}><label>Origem<select name="sourceType" defaultValue={modal.data?.sourceType||"business"}><option value="business">Lucro realizado de uma empresa</option><option value="investments">Lucro dos investimentos</option></select></label><label>Empresa<select name="businessId" defaultValue={modal.data?.businessId||d.activeBusiness.id}>{d.businesses.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><Field name="percentage" label="Percentual (%)" type="number" value={modal.data?.percentage||15} required/></Modal>}
 </>}

export function PersonalAssetsPanel({d}:any){
 const[modal,setModal]=useState<any>(null),[error,setError]=useState(""),qc=useQueryClient();const m=useMutation({mutationFn:postAction,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["app-data"]});setModal(null);setError("")},onError:(e:any)=>setError(e?.message||"Não foi possível salvar o patrimônio")});const x=d.personalAssets,labels:any={property:"Imóvel",vehicle:"Veículo",equity:"Participação acionária"},icons:any={property:House,vehicle:Car,equity:Handshake};
 return <><div className={styles.summary}><article><Landmark/><small>VALOR ATUAL DOS BENS</small><strong>{brl(x.grossValue)}</strong></article><article><CreditCard/><small>SALDO AINDA DEVIDO</small><strong className={styles.red}>{brl(x.outstandingDebt)}</strong></article><article><TrendingUp/><small>PATRIMÔNIO LÍQUIDO PESSOAL</small><strong className={styles.green}>{brl(x.netValue)}</strong></article></div>
 <Shell title="Patrimônio pessoal" subtitle="Imóveis, veículos e participações separados das empresas e da carteira de investimentos." action={<Button onClick={()=>setModal({})}><Plus size={15}/> Novo patrimônio</Button>}>
  <div className={styles.investGrid}>{x.assets.length?x.assets.map((a:any)=>{const I=icons[a.assetType]||Landmark,net=Math.max(0,Number(a.currentValue)-Number(a.outstandingDebt));return <article key={a.id}><I/><small>{labels[a.assetType]||a.assetType}</small><h3>{a.name}</h3><p>{a.description||"Sem descrição adicional"}</p><b>{brl(net)}</b><span>Valor atual: {brl(a.currentValue)} · saldo devido: {brl(a.outstandingDebt)}</span>{a.assetType==="equity"&&a.ownershipPercentage!=null&&<span>Participação: {Number(a.ownershipPercentage)}%</span>}<div className={styles.cardActions}><Button variant="outline" onClick={()=>setModal(a)}>Editar</Button><button type="button" onClick={async()=>{if(confirm("Arquivar este patrimônio?"))await m.mutateAsync({action:"archivePersonalAsset",assetId:String(a.id)})}}><Trash2 size={15}/></button></div></article>}):<p className={styles.empty}>Nenhum imóvel, veículo ou participação acionária cadastrado.</p>}</div>
 </Shell>{modal&&<Modal title={modal.id?"Editar patrimônio":"Cadastrar patrimônio"} close={()=>setModal(null)} busy={m.isPending} error={error} submit={(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);m.mutate({action:"upsertPersonalAsset",assetId:modal.id?String(modal.id):undefined,assetType:String(f.get("assetType")) as any,name:String(f.get("name")),description:String(f.get("description")||""),currentValue:Number(f.get("currentValue")),amountPaid:Number(f.get("amountPaid")),outstandingDebt:Number(f.get("outstandingDebt")),ownershipPercentage:f.get("ownershipPercentage")?Number(f.get("ownershipPercentage")):undefined,acquisitionDate:String(f.get("acquisitionDate")||""),notes:String(f.get("notes")||"")})}}><label>Tipo<select name="assetType" defaultValue={modal.assetType||"property"}><option value="property">Imóvel</option><option value="vehicle">Veículo</option><option value="equity">Participação acionária</option></select></label><Field name="name" label="Nome do bem ou participação" value={modal.name} required/><Field name="description" label="Descrição" value={modal.description}/><Field name="currentValue" label="Valor atual estimado" type="number" value={modal.currentValue} required/><Field name="amountPaid" label="Valor já pago" type="number" value={modal.amountPaid} required/><Field name="outstandingDebt" label="Saldo ainda devido" type="number" value={modal.outstandingDebt} required/><Field name="ownershipPercentage" label="Percentual de participação, quando aplicável (%)" type="number" value={modal.ownershipPercentage}/><Field name="acquisitionDate" label="Data de aquisição" type="date" value={modal.acquisitionDate?new Date(modal.acquisitionDate).toISOString().slice(0,10):""}/><Field name="notes" label="Observações" value={modal.notes}/></Modal>}</>
}

export function InvestmentsPanel({d}:any){
 const[modal,setModal]=useState<any>(null),qc=useQueryClient();const m=useMutation({mutationFn:postAction,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["app-data"]});setModal(null)}});const x=d.investments;const labels:any={stock:"Ação",crypto:"Criptomoeda",fund:"Fundo",property:"Imóvel",fixed_income:"Renda fixa",other:"Outro"};
 return <><div className={styles.summary}><article><Landmark/><small>VALOR INVESTIDO</small><strong>{brl(x.totalCost)}</strong></article><article><WalletCards/><small>VALOR ATUAL</small><strong>{brl(x.currentValue)}</strong></article><article><TrendingUp/><small>RESULTADO DA CARTEIRA</small><strong className={x.profit>=0?styles.green:styles.red}>{brl(x.profit)}</strong></article></div>
 <Shell title="Carteira de investimentos" subtitle="Atualize manualmente a cotação; cada atualização mensal fica registrada para o pró-labore do mês seguinte." action={<Button onClick={()=>setModal({})}><Plus size={15}/> Investimento</Button>}>
  <div className={styles.investGrid}>{x.assets.length?x.assets.map((a:any)=><article key={a.id}><small>{labels[a.assetType]||a.assetType}</small><h3>{a.name} {a.symbol&&<em>{a.symbol}</em>}</h3><p>{Number(a.quantity)} unidades</p><b>{brl(Number(a.quantity)*Number(a.currentUnitPrice))}</b><span>Resultado: {brl((Number(a.currentUnitPrice)-Number(a.averageCost))*Number(a.quantity))}</span><div className={styles.cardActions}><Button variant="outline" onClick={()=>setModal(a)}>Atualizar</Button><button type="button" onClick={async()=>{if(confirm("Arquivar investimento?"))await m.mutateAsync({action:"archiveInvestment",assetId:String(a.id)})}}><Trash2 size={15}/></button></div></article>):<p className={styles.empty}>Nenhum investimento cadastrado.</p>}</div>
 </Shell>{modal&&<Modal title={modal.id?"Atualizar investimento":"Cadastrar investimento"} close={()=>setModal(null)} busy={m.isPending} submit={(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);m.mutate({action:"upsertInvestment",assetId:modal.id?String(modal.id):undefined,name:String(f.get("name")),assetType:String(f.get("assetType")) as any,quantity:Number(f.get("quantity")),averageCost:Number(f.get("averageCost")),currentUnitPrice:Number(f.get("currentUnitPrice")),symbol:String(f.get("symbol")||""),notes:String(f.get("notes")||"")})}}><Field name="name" label="Nome do investimento" value={modal.name} required/><label>Categoria<select name="assetType" defaultValue={modal.assetType||"stock"}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{String(v)}</option>)}</select></label><Field name="symbol" label="Código/símbolo" value={modal.symbol}/><Field name="quantity" label="Quantidade" type="number" value={modal.quantity||1} required/><Field name="averageCost" label="Custo médio por unidade" type="number" value={modal.averageCost} required/><Field name="currentUnitPrice" label="Cotação/valor atual por unidade" type="number" value={modal.currentUnitPrice} required/><Field name="notes" label="Observações" value={modal.notes}/></Modal>}</>
}
